// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package inference

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_PoCValidationSnapshot_4_list)(nil)

type _PoCValidationSnapshot_4_list struct {
	list *[]*ValidatorWeight
}

func (x *_PoCValidationSnapshot_4_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_PoCValidationSnapshot_4_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_PoCValidationSnapshot_4_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*ValidatorWeight)
	(*x.list)[i] = concreteValue
}

func (x *_PoCValidationSnapshot_4_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*ValidatorWeight)
	*x.list = append(*x.list, concreteValue)
}

func (x *_PoCValidationSnapshot_4_list) AppendMutable() protoreflect.Value {
	v := new(ValidatorWeight)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_PoCValidationSnapshot_4_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_PoCValidationSnapshot_4_list) NewElement() protoreflect.Value {
	v := new(ValidatorWeight)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_PoCValidationSnapshot_4_list) IsValid() bool {
	return x.list != nil
}

var (
	md_PoCValidationSnapshot                            protoreflect.MessageDescriptor
	fd_PoCValidationSnapshot_poc_stage_start_height     protoreflect.FieldDescriptor
	fd_PoCValidationSnapshot_snapshot_height            protoreflect.FieldDescriptor
	fd_PoCValidationSnapshot_app_hash                   protoreflect.FieldDescriptor
	fd_PoCValidationSnapshot_validator_weights          protoreflect.FieldDescriptor
	fd_PoCValidationSnapshot_generation_start_timestamp protoreflect.FieldDescriptor
	fd_PoCValidationSnapshot_exchange_end_timestamp     protoreflect.FieldDescriptor
)

func init() {
	file_inference_inference_poc_validation_snapshot_proto_init()
	md_PoCValidationSnapshot = File_inference_inference_poc_validation_snapshot_proto.Messages().ByName("PoCValidationSnapshot")
	fd_PoCValidationSnapshot_poc_stage_start_height = md_PoCValidationSnapshot.Fields().ByName("poc_stage_start_height")
	fd_PoCValidationSnapshot_snapshot_height = md_PoCValidationSnapshot.Fields().ByName("snapshot_height")
	fd_PoCValidationSnapshot_app_hash = md_PoCValidationSnapshot.Fields().ByName("app_hash")
	fd_PoCValidationSnapshot_validator_weights = md_PoCValidationSnapshot.Fields().ByName("validator_weights")
	fd_PoCValidationSnapshot_generation_start_timestamp = md_PoCValidationSnapshot.Fields().ByName("generation_start_timestamp")
	fd_PoCValidationSnapshot_exchange_end_timestamp = md_PoCValidationSnapshot.Fields().ByName("exchange_end_timestamp")
}

var _ protoreflect.Message = (*fastReflection_PoCValidationSnapshot)(nil)

type fastReflection_PoCValidationSnapshot PoCValidationSnapshot

func (x *PoCValidationSnapshot) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PoCValidationSnapshot)(x)
}

func (x *PoCValidationSnapshot) slowProtoReflect() protoreflect.Message {
	mi := &file_inference_inference_poc_validation_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PoCValidationSnapshot_messageType fastReflection_PoCValidationSnapshot_messageType
var _ protoreflect.MessageType = fastReflection_PoCValidationSnapshot_messageType{}

type fastReflection_PoCValidationSnapshot_messageType struct{}

func (x fastReflection_PoCValidationSnapshot_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PoCValidationSnapshot)(nil)
}
func (x fastReflection_PoCValidationSnapshot_messageType) New() protoreflect.Message {
	return new(fastReflection_PoCValidationSnapshot)
}
func (x fastReflection_PoCValidationSnapshot_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PoCValidationSnapshot
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PoCValidationSnapshot) Descriptor() protoreflect.MessageDescriptor {
	return md_PoCValidationSnapshot
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PoCValidationSnapshot) Type() protoreflect.MessageType {
	return _fastReflection_PoCValidationSnapshot_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PoCValidationSnapshot) New() protoreflect.Message {
	return new(fastReflection_PoCValidationSnapshot)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PoCValidationSnapshot) Interface() protoreflect.ProtoMessage {
	return (*PoCValidationSnapshot)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PoCValidationSnapshot) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.PocStageStartHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.PocStageStartHeight)
		if !f(fd_PoCValidationSnapshot_poc_stage_start_height, value) {
			return
		}
	}
	if x.SnapshotHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.SnapshotHeight)
		if !f(fd_PoCValidationSnapshot_snapshot_height, value) {
			return
		}
	}
	if x.AppHash != "" {
		value := protoreflect.ValueOfString(x.AppHash)
		if !f(fd_PoCValidationSnapshot_app_hash, value) {
			return
		}
	}
	if len(x.ValidatorWeights) != 0 {
		value := protoreflect.ValueOfList(&_PoCValidationSnapshot_4_list{list: &x.ValidatorWeights})
		if !f(fd_PoCValidationSnapshot_validator_weights, value) {
			return
		}
	}
	if x.GenerationStartTimestamp != int64(0) {
		value := protoreflect.ValueOfInt64(x.GenerationStartTimestamp)
		if !f(fd_PoCValidationSnapshot_generation_start_timestamp, value) {
			return
		}
	}
	if x.ExchangeEndTimestamp != int64(0) {
		value := protoreflect.ValueOfInt64(x.ExchangeEndTimestamp)
		if !f(fd_PoCValidationSnapshot_exchange_end_timestamp, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PoCValidationSnapshot) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "inference.inference.PoCValidationSnapshot.poc_stage_start_height":
		return x.PocStageStartHeight != int64(0)
	case "inference.inference.PoCValidationSnapshot.snapshot_height":
		return x.SnapshotHeight != int64(0)
	case "inference.inference.PoCValidationSnapshot.app_hash":
		return x.AppHash != ""
	case "inference.inference.PoCValidationSnapshot.validator_weights":
		return len(x.ValidatorWeights) != 0
	case "inference.inference.PoCValidationSnapshot.generation_start_timestamp":
		return x.GenerationStartTimestamp != int64(0)
	case "inference.inference.PoCValidationSnapshot.exchange_end_timestamp":
		return x.ExchangeEndTimestamp != int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCValidationSnapshot"))
		}
		panic(fmt.Errorf("message inference.inference.PoCValidationSnapshot does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoCValidationSnapshot) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "inference.inference.PoCValidationSnapshot.poc_stage_start_height":
		x.PocStageStartHeight = int64(0)
	case "inference.inference.PoCValidationSnapshot.snapshot_height":
		x.SnapshotHeight = int64(0)
	case "inference.inference.PoCValidationSnapshot.app_hash":
		x.AppHash = ""
	case "inference.inference.PoCValidationSnapshot.validator_weights":
		x.ValidatorWeights = nil
	case "inference.inference.PoCValidationSnapshot.generation_start_timestamp":
		x.GenerationStartTimestamp = int64(0)
	case "inference.inference.PoCValidationSnapshot.exchange_end_timestamp":
		x.ExchangeEndTimestamp = int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCValidationSnapshot"))
		}
		panic(fmt.Errorf("message inference.inference.PoCValidationSnapshot does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PoCValidationSnapshot) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "inference.inference.PoCValidationSnapshot.poc_stage_start_height":
		value := x.PocStageStartHeight
		return protoreflect.ValueOfInt64(value)
	case "inference.inference.PoCValidationSnapshot.snapshot_height":
		value := x.SnapshotHeight
		return protoreflect.ValueOfInt64(value)
	case "inference.inference.PoCValidationSnapshot.app_hash":
		value := x.AppHash
		return protoreflect.ValueOfString(value)
	case "inference.inference.PoCValidationSnapshot.validator_weights":
		if len(x.ValidatorWeights) == 0 {
			return protoreflect.ValueOfList(&_PoCValidationSnapshot_4_list{})
		}
		listValue := &_PoCValidationSnapshot_4_list{list: &x.ValidatorWeights}
		return protoreflect.ValueOfList(listValue)
	case "inference.inference.PoCValidationSnapshot.generation_start_timestamp":
		value := x.GenerationStartTimestamp
		return protoreflect.ValueOfInt64(value)
	case "inference.inference.PoCValidationSnapshot.exchange_end_timestamp":
		value := x.ExchangeEndTimestamp
		return protoreflect.ValueOfInt64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCValidationSnapshot"))
		}
		panic(fmt.Errorf("message inference.inference.PoCValidationSnapshot does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoCValidationSnapshot) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "inference.inference.PoCValidationSnapshot.poc_stage_start_height":
		x.PocStageStartHeight = value.Int()
	case "inference.inference.PoCValidationSnapshot.snapshot_height":
		x.SnapshotHeight = value.Int()
	case "inference.inference.PoCValidationSnapshot.app_hash":
		x.AppHash = value.Interface().(string)
	case "inference.inference.PoCValidationSnapshot.validator_weights":
		lv := value.List()
		clv := lv.(*_PoCValidationSnapshot_4_list)
		x.ValidatorWeights = *clv.list
	case "inference.inference.PoCValidationSnapshot.generation_start_timestamp":
		x.GenerationStartTimestamp = value.Int()
	case "inference.inference.PoCValidationSnapshot.exchange_end_timestamp":
		x.ExchangeEndTimestamp = value.Int()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCValidationSnapshot"))
		}
		panic(fmt.Errorf("message inference.inference.PoCValidationSnapshot does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoCValidationSnapshot) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.PoCValidationSnapshot.validator_weights":
		if x.ValidatorWeights == nil {
			x.ValidatorWeights = []*ValidatorWeight{}
		}
		value := &_PoCValidationSnapshot_4_list{list: &x.ValidatorWeights}
		return protoreflect.ValueOfList(value)
	case "inference.inference.PoCValidationSnapshot.poc_stage_start_height":
		panic(fmt.Errorf("field poc_stage_start_height of message inference.inference.PoCValidationSnapshot is not mutable"))
	case "inference.inference.PoCValidationSnapshot.snapshot_height":
		panic(fmt.Errorf("field snapshot_height of message inference.inference.PoCValidationSnapshot is not mutable"))
	case "inference.inference.PoCValidationSnapshot.app_hash":
		panic(fmt.Errorf("field app_hash of message inference.inference.PoCValidationSnapshot is not mutable"))
	case "inference.inference.PoCValidationSnapshot.generation_start_timestamp":
		panic(fmt.Errorf("field generation_start_timestamp of message inference.inference.PoCValidationSnapshot is not mutable"))
	case "inference.inference.PoCValidationSnapshot.exchange_end_timestamp":
		panic(fmt.Errorf("field exchange_end_timestamp of message inference.inference.PoCValidationSnapshot is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCValidationSnapshot"))
		}
		panic(fmt.Errorf("message inference.inference.PoCValidationSnapshot does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PoCValidationSnapshot) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.PoCValidationSnapshot.poc_stage_start_height":
		return protoreflect.ValueOfInt64(int64(0))
	case "inference.inference.PoCValidationSnapshot.snapshot_height":
		return protoreflect.ValueOfInt64(int64(0))
	case "inference.inference.PoCValidationSnapshot.app_hash":
		return protoreflect.ValueOfString("")
	case "inference.inference.PoCValidationSnapshot.validator_weights":
		list := []*ValidatorWeight{}
		return protoreflect.ValueOfList(&_PoCValidationSnapshot_4_list{list: &list})
	case "inference.inference.PoCValidationSnapshot.generation_start_timestamp":
		return protoreflect.ValueOfInt64(int64(0))
	case "inference.inference.PoCValidationSnapshot.exchange_end_timestamp":
		return protoreflect.ValueOfInt64(int64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCValidationSnapshot"))
		}
		panic(fmt.Errorf("message inference.inference.PoCValidationSnapshot does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PoCValidationSnapshot) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in inference.inference.PoCValidationSnapshot", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PoCValidationSnapshot) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoCValidationSnapshot) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PoCValidationSnapshot) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PoCValidationSnapshot) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PoCValidationSnapshot)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.PocStageStartHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.PocStageStartHeight))
		}
		if x.SnapshotHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.SnapshotHeight))
		}
		l = len(x.AppHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.ValidatorWeights) > 0 {
			for _, e := range x.ValidatorWeights {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.GenerationStartTimestamp != 0 {
			n += 1 + runtime.Sov(uint64(x.GenerationStartTimestamp))
		}
		if x.ExchangeEndTimestamp != 0 {
			n += 1 + runtime.Sov(uint64(x.ExchangeEndTimestamp))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PoCValidationSnapshot)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.ExchangeEndTimestamp != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ExchangeEndTimestamp))
			i--
			dAtA[i] = 0x30
		}
		if x.GenerationStartTimestamp != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.GenerationStartTimestamp))
			i--
			dAtA[i] = 0x28
		}
		if len(x.ValidatorWeights) > 0 {
			for iNdEx := len(x.ValidatorWeights) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.ValidatorWeights[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x22
			}
		}
		if len(x.AppHash) > 0 {
			i -= len(x.AppHash)
			copy(dAtA[i:], x.AppHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AppHash)))
			i--
			dAtA[i] = 0x1a
		}
		if x.SnapshotHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SnapshotHeight))
			i--
			dAtA[i] = 0x10
		}
		if x.PocStageStartHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.PocStageStartHeight))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PoCValidationSnapshot)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PoCValidationSnapshot: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PoCValidationSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PocStageStartHeight", wireType)
				}
				x.PocStageStartHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.PocStageStartHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SnapshotHeight", wireType)
				}
				x.SnapshotHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SnapshotHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AppHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AppHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ValidatorWeights", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ValidatorWeights = append(x.ValidatorWeights, &ValidatorWeight{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.ValidatorWeights[len(x.ValidatorWeights)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GenerationStartTimestamp", wireType)
				}
				x.GenerationStartTimestamp = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.GenerationStartTimestamp |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ExchangeEndTimestamp", wireType)
				}
				x.ExchangeEndTimestamp = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ExchangeEndTimestamp |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_ValidatorWeight         protoreflect.MessageDescriptor
	fd_ValidatorWeight_address protoreflect.FieldDescriptor
	fd_ValidatorWeight_weight  protoreflect.FieldDescriptor
)

func init() {
	file_inference_inference_poc_validation_snapshot_proto_init()
	md_ValidatorWeight = File_inference_inference_poc_validation_snapshot_proto.Messages().ByName("ValidatorWeight")
	fd_ValidatorWeight_address = md_ValidatorWeight.Fields().ByName("address")
	fd_ValidatorWeight_weight = md_ValidatorWeight.Fields().ByName("weight")
}

var _ protoreflect.Message = (*fastReflection_ValidatorWeight)(nil)

type fastReflection_ValidatorWeight ValidatorWeight

func (x *ValidatorWeight) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ValidatorWeight)(x)
}

func (x *ValidatorWeight) slowProtoReflect() protoreflect.Message {
	mi := &file_inference_inference_poc_validation_snapshot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ValidatorWeight_messageType fastReflection_ValidatorWeight_messageType
var _ protoreflect.MessageType = fastReflection_ValidatorWeight_messageType{}

type fastReflection_ValidatorWeight_messageType struct{}

func (x fastReflection_ValidatorWeight_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ValidatorWeight)(nil)
}
func (x fastReflection_ValidatorWeight_messageType) New() protoreflect.Message {
	return new(fastReflection_ValidatorWeight)
}
func (x fastReflection_ValidatorWeight_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ValidatorWeight
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ValidatorWeight) Descriptor() protoreflect.MessageDescriptor {
	return md_ValidatorWeight
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ValidatorWeight) Type() protoreflect.MessageType {
	return _fastReflection_ValidatorWeight_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ValidatorWeight) New() protoreflect.Message {
	return new(fastReflection_ValidatorWeight)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ValidatorWeight) Interface() protoreflect.ProtoMessage {
	return (*ValidatorWeight)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ValidatorWeight) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Address != "" {
		value := protoreflect.ValueOfString(x.Address)
		if !f(fd_ValidatorWeight_address, value) {
			return
		}
	}
	if x.Weight != int64(0) {
		value := protoreflect.ValueOfInt64(x.Weight)
		if !f(fd_ValidatorWeight_weight, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ValidatorWeight) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "inference.inference.ValidatorWeight.address":
		return x.Address != ""
	case "inference.inference.ValidatorWeight.weight":
		return x.Weight != int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.ValidatorWeight"))
		}
		panic(fmt.Errorf("message inference.inference.ValidatorWeight does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ValidatorWeight) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "inference.inference.ValidatorWeight.address":
		x.Address = ""
	case "inference.inference.ValidatorWeight.weight":
		x.Weight = int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.ValidatorWeight"))
		}
		panic(fmt.Errorf("message inference.inference.ValidatorWeight does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ValidatorWeight) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "inference.inference.ValidatorWeight.address":
		value := x.Address
		return protoreflect.ValueOfString(value)
	case "inference.inference.ValidatorWeight.weight":
		value := x.Weight
		return protoreflect.ValueOfInt64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.ValidatorWeight"))
		}
		panic(fmt.Errorf("message inference.inference.ValidatorWeight does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ValidatorWeight) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "inference.inference.ValidatorWeight.address":
		x.Address = value.Interface().(string)
	case "inference.inference.ValidatorWeight.weight":
		x.Weight = value.Int()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.ValidatorWeight"))
		}
		panic(fmt.Errorf("message inference.inference.ValidatorWeight does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ValidatorWeight) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.ValidatorWeight.address":
		panic(fmt.Errorf("field address of message inference.inference.ValidatorWeight is not mutable"))
	case "inference.inference.ValidatorWeight.weight":
		panic(fmt.Errorf("field weight of message inference.inference.ValidatorWeight is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.ValidatorWeight"))
		}
		panic(fmt.Errorf("message inference.inference.ValidatorWeight does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ValidatorWeight) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.ValidatorWeight.address":
		return protoreflect.ValueOfString("")
	case "inference.inference.ValidatorWeight.weight":
		return protoreflect.ValueOfInt64(int64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.ValidatorWeight"))
		}
		panic(fmt.Errorf("message inference.inference.ValidatorWeight does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ValidatorWeight) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in inference.inference.ValidatorWeight", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ValidatorWeight) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ValidatorWeight) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ValidatorWeight) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ValidatorWeight) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ValidatorWeight)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Address)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Weight != 0 {
			n += 1 + runtime.Sov(uint64(x.Weight))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ValidatorWeight)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Weight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Weight))
			i--
			dAtA[i] = 0x10
		}
		if len(x.Address) > 0 {
			i -= len(x.Address)
			copy(dAtA[i:], x.Address)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Address)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ValidatorWeight)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ValidatorWeight: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ValidatorWeight: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Address = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
				}
				x.Weight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Weight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: inference/inference/poc_validation_snapshot.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PoCValidationSnapshot captures validator weights at validation phase start
// for deterministic sampling synchronization between chain and DAPI.
type PoCValidationSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PocStageStartHeight      int64              `protobuf:"varint,1,opt,name=poc_stage_start_height,json=pocStageStartHeight,proto3" json:"poc_stage_start_height,omitempty"`
	SnapshotHeight           int64              `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	AppHash                  string             `protobuf:"bytes,3,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	ValidatorWeights         []*ValidatorWeight `protobuf:"bytes,4,rep,name=validator_weights,json=validatorWeights,proto3" json:"validator_weights,omitempty"`
	GenerationStartTimestamp int64              `protobuf:"varint,5,opt,name=generation_start_timestamp,json=generationStartTimestamp,proto3" json:"generation_start_timestamp,omitempty"`
	ExchangeEndTimestamp     int64              `protobuf:"varint,6,opt,name=exchange_end_timestamp,json=exchangeEndTimestamp,proto3" json:"exchange_end_timestamp,omitempty"`
}

func (x *PoCValidationSnapshot) Reset() {
	*x = PoCValidationSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inference_inference_poc_validation_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoCValidationSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoCValidationSnapshot) ProtoMessage() {}

// Deprecated: Use PoCValidationSnapshot.ProtoReflect.Descriptor instead.
func (*PoCValidationSnapshot) Descriptor() ([]byte, []int) {
	return file_inference_inference_poc_validation_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *PoCValidationSnapshot) GetPocStageStartHeight() int64 {
	if x != nil {
		return x.PocStageStartHeight
	}
	return 0
}

func (x *PoCValidationSnapshot) GetSnapshotHeight() int64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *PoCValidationSnapshot) GetAppHash() string {
	if x != nil {
		return x.AppHash
	}
	return ""
}

func (x *PoCValidationSnapshot) GetValidatorWeights() []*ValidatorWeight {
	if x != nil {
		return x.ValidatorWeights
	}
	return nil
}

func (x *PoCValidationSnapshot) GetGenerationStartTimestamp() int64 {
	if x != nil {
		return x.GenerationStartTimestamp
	}
	return 0
}

func (x *PoCValidationSnapshot) GetExchangeEndTimestamp() int64 {
	if x != nil {
		return x.ExchangeEndTimestamp
	}
	return 0
}

type ValidatorWeight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Weight  int64  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *ValidatorWeight) Reset() {
	*x = ValidatorWeight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inference_inference_poc_validation_snapshot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorWeight) ProtoMessage() {}

// Deprecated: Use ValidatorWeight.ProtoReflect.Descriptor instead.
func (*ValidatorWeight) Descriptor() ([]byte, []int) {
	return file_inference_inference_poc_validation_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatorWeight) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ValidatorWeight) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_inference_inference_poc_validation_snapshot_proto protoreflect.FileDescriptor

var file_inference_inference_poc_validation_snapshot_proto_rawDesc = []byte{
	0x0a, 0x31, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x6f, 0x63, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69,
	0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xd7, 0x02, 0x0a, 0x15, 0x50, 0x6f, 0x43,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x33, 0x0a, 0x16, 0x70, 0x6f, 0x63, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x13, 0x70, 0x6f, 0x63, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x48, 0x61, 0x73, 0x68, 0x12, 0x51, 0x0a, 0x11, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x10, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x3c,
	0x0a, 0x1a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x18, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x34, 0x0a, 0x16,
	0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x43, 0x0a, 0x0f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0xc8, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e,
	0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x42, 0x1a, 0x50, 0x6f, 0x63, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x24, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0xa2, 0x02, 0x03, 0x49, 0x49, 0x58, 0xaa, 0x02, 0x13,
	0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0xca, 0x02, 0x13, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c,
	0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0xe2, 0x02, 0x1f, 0x49, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x14, 0x49, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x3a, 0x3a, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inference_inference_poc_validation_snapshot_proto_rawDescOnce sync.Once
	file_inference_inference_poc_validation_snapshot_proto_rawDescData = file_inference_inference_poc_validation_snapshot_proto_rawDesc
)

func file_inference_inference_poc_validation_snapshot_proto_rawDescGZIP() []byte {
	file_inference_inference_poc_validation_snapshot_proto_rawDescOnce.Do(func() {
		file_inference_inference_poc_validation_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_inference_inference_poc_validation_snapshot_proto_rawDescData)
	})
	return file_inference_inference_poc_validation_snapshot_proto_rawDescData
}

var file_inference_inference_poc_validation_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inference_inference_poc_validation_snapshot_proto_goTypes = []interface{}{
	(*PoCValidationSnapshot)(nil), // 0: inference.inference.PoCValidationSnapshot
	(*ValidatorWeight)(nil),       // 1: inference.inference.ValidatorWeight
}
var file_inference_inference_poc_validation_snapshot_proto_depIdxs = []int32{
	1, // 0: inference.inference.PoCValidationSnapshot.validator_weights:type_name -> inference.inference.ValidatorWeight
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inference_inference_poc_validation_snapshot_proto_init() }
func file_inference_inference_poc_validation_snapshot_proto_init() {
	if File_inference_inference_poc_validation_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inference_inference_poc_validation_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoCValidationSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inference_inference_poc_validation_snapshot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorWeight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inference_inference_poc_validation_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inference_inference_poc_validation_snapshot_proto_goTypes,
		DependencyIndexes: file_inference_inference_poc_validation_snapshot_proto_depIdxs,
		MessageInfos:      file_inference_inference_poc_validation_snapshot_proto_msgTypes,
	}.Build()
	File_inference_inference_poc_validation_snapshot_proto = out.File
	file_inference_inference_poc_validation_snapshot_proto_rawDesc = nil
	file_inference_inference_poc_validation_snapshot_proto_goTypes = nil
	file_inference_inference_poc_validation_snapshot_proto_depIdxs = nil
}
