// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/poc_validation_snapshot.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PoCValidationSnapshot captures validator weights at validation phase start
// for deterministic sampling synchronization between chain and DAPI.
type PoCValidationSnapshot struct {
	PocStageStartHeight      int64              `protobuf:"varint,1,opt,name=poc_stage_start_height,json=pocStageStartHeight,proto3" json:"poc_stage_start_height,omitempty"`
	SnapshotHeight           int64              `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	AppHash                  string             `protobuf:"bytes,3,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	ValidatorWeights         []*ValidatorWeight `protobuf:"bytes,4,rep,name=validator_weights,json=validatorWeights,proto3" json:"validator_weights,omitempty"`
	GenerationStartTimestamp int64              `protobuf:"varint,5,opt,name=generation_start_timestamp,json=generationStartTimestamp,proto3" json:"generation_start_timestamp,omitempty"`
	ExchangeEndTimestamp     int64              `protobuf:"varint,6,opt,name=exchange_end_timestamp,json=exchangeEndTimestamp,proto3" json:"exchange_end_timestamp,omitempty"`
}

func (m *PoCValidationSnapshot) Reset()         { *m = PoCValidationSnapshot{} }
func (m *PoCValidationSnapshot) String() string { return proto.CompactTextString(m) }
func (*PoCValidationSnapshot) ProtoMessage()    {}
func (*PoCValidationSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d995e793da19be, []int{0}
}
func (m *PoCValidationSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCValidationSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCValidationSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCValidationSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCValidationSnapshot.Merge(m, src)
}
func (m *PoCValidationSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *PoCValidationSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCValidationSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_PoCValidationSnapshot proto.InternalMessageInfo

func (m *PoCValidationSnapshot) GetPocStageStartHeight() int64 {
	if m != nil {
		return m.PocStageStartHeight
	}
	return 0
}

func (m *PoCValidationSnapshot) GetSnapshotHeight() int64 {
	if m != nil {
		return m.SnapshotHeight
	}
	return 0
}

func (m *PoCValidationSnapshot) GetAppHash() string {
	if m != nil {
		return m.AppHash
	}
	return ""
}

func (m *PoCValidationSnapshot) GetValidatorWeights() []*ValidatorWeight {
	if m != nil {
		return m.ValidatorWeights
	}
	return nil
}

func (m *PoCValidationSnapshot) GetGenerationStartTimestamp() int64 {
	if m != nil {
		return m.GenerationStartTimestamp
	}
	return 0
}

func (m *PoCValidationSnapshot) GetExchangeEndTimestamp() int64 {
	if m != nil {
		return m.ExchangeEndTimestamp
	}
	return 0
}

type ValidatorWeight struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Weight  int64  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (m *ValidatorWeight) Reset()         { *m = ValidatorWeight{} }
func (m *ValidatorWeight) String() string { return proto.CompactTextString(m) }
func (*ValidatorWeight) ProtoMessage()    {}
func (*ValidatorWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d995e793da19be, []int{1}
}
func (m *ValidatorWeight) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorWeight.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorWeight.Merge(m, src)
}
func (m *ValidatorWeight) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorWeight.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorWeight proto.InternalMessageInfo

func (m *ValidatorWeight) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ValidatorWeight) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*PoCValidationSnapshot)(nil), "inference.inference.PoCValidationSnapshot")
	proto.RegisterType((*ValidatorWeight)(nil), "inference.inference.ValidatorWeight")
}

func init() {
	proto.RegisterFile("inference/inference/poc_validation_snapshot.proto", fileDescriptor_b9d995e793da19be)
}

var fileDescriptor_b9d995e793da19be = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4e, 0x32, 0x31,
	0x14, 0xc5, 0x19, 0xf8, 0x3e, 0xd0, 0x9a, 0x88, 0x16, 0x25, 0xa3, 0x8b, 0x09, 0x21, 0x26, 0xb2,
	0x1a, 0xa2, 0xe8, 0xce, 0x95, 0xc4, 0x84, 0x9d, 0x0a, 0x06, 0x13, 0x37, 0x93, 0xd2, 0xa9, 0xd3,
	0x26, 0xd2, 0x36, 0x6d, 0xf9, 0xe3, 0x5b, 0xf8, 0x58, 0x2e, 0xd9, 0xe9, 0xd2, 0xc0, 0x8b, 0x98,
	0xa9, 0x33, 0xc3, 0x48, 0xdc, 0x4c, 0x6e, 0x7b, 0x7e, 0x67, 0x7a, 0xcf, 0xcd, 0x05, 0x67, 0x8c,
	0x3f, 0x13, 0x45, 0x38, 0x26, 0xed, 0x75, 0x25, 0x05, 0x0e, 0xa6, 0xe8, 0x85, 0x85, 0xc8, 0x30,
	0xc1, 0x03, 0xcd, 0x91, 0xd4, 0x54, 0x18, 0x5f, 0x2a, 0x61, 0x04, 0xac, 0x65, 0xa0, 0x9f, 0x55,
	0xcd, 0x8f, 0x22, 0x38, 0xbc, 0x13, 0xdd, 0x61, 0xe6, 0x1a, 0x24, 0x26, 0xd8, 0x01, 0xf5, 0xf8,
	0x7f, 0xda, 0xa0, 0x88, 0xc4, 0x5f, 0x65, 0x02, 0x4a, 0x58, 0x44, 0x8d, 0xeb, 0x34, 0x9c, 0x56,
	0xa9, 0x5f, 0x93, 0x02, 0x0f, 0x62, 0x71, 0x10, 0x6b, 0x3d, 0x2b, 0xc1, 0x53, 0x50, 0x4d, 0x5f,
	0x4d, 0xe9, 0xa2, 0xa5, 0x77, 0xd3, 0xeb, 0x04, 0x3c, 0x02, 0x5b, 0x48, 0xca, 0x80, 0x22, 0x4d,
	0xdd, 0x52, 0xc3, 0x69, 0x6d, 0xf7, 0x2b, 0x48, 0xca, 0x1e, 0xd2, 0x14, 0xde, 0x83, 0xfd, 0x24,
	0x84, 0x50, 0xc1, 0xcc, 0xe2, 0xda, 0xfd, 0xd7, 0x28, 0xb5, 0x76, 0xce, 0x4f, 0xfc, 0x3f, 0x32,
	0xf8, 0xc3, 0x94, 0x7e, 0xb4, 0x70, 0x7f, 0x6f, 0xfa, 0xfb, 0x42, 0xc3, 0x2b, 0x70, 0x1c, 0x11,
	0x4e, 0x54, 0x32, 0x17, 0x1b, 0xc6, 0xb0, 0x31, 0xd1, 0x06, 0x8d, 0xa5, 0xfb, 0xdf, 0x76, 0xe8,
	0xae, 0x09, 0x9b, 0xe8, 0x21, 0xd5, 0xe1, 0x05, 0xa8, 0x93, 0x39, 0xa6, 0x88, 0x47, 0x24, 0x20,
	0x3c, 0xcc, 0x39, 0xcb, 0xd6, 0x79, 0x90, 0xaa, 0x37, 0x3c, 0xcc, 0x5c, 0xcd, 0x2e, 0xa8, 0x6e,
	0x34, 0x06, 0x5d, 0x50, 0x41, 0x61, 0xa8, 0x88, 0xd6, 0x76, 0x86, 0x71, 0xe6, 0x9f, 0x23, 0xac,
	0x83, 0xf2, 0x2c, 0x3f, 0xae, 0xe4, 0x74, 0x7d, 0xfb, 0xbe, 0xf4, 0x9c, 0xc5, 0xd2, 0x73, 0xbe,
	0x96, 0x9e, 0xf3, 0xb6, 0xf2, 0x0a, 0x8b, 0x95, 0x57, 0xf8, 0x5c, 0x79, 0x85, 0xa7, 0xcb, 0x88,
	0x19, 0x3a, 0x19, 0xf9, 0x58, 0x8c, 0xdb, 0x52, 0x89, 0x70, 0x82, 0x8d, 0xc6, 0x6c, 0x63, 0x21,
	0xe6, 0xb9, 0xda, 0xbc, 0x4a, 0xa2, 0x47, 0x65, 0xbb, 0x0b, 0x9d, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x2b, 0xf1, 0x4d, 0x25, 0x40, 0x02, 0x00, 0x00,
}

func (m *PoCValidationSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCValidationSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCValidationSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExchangeEndTimestamp != 0 {
		i = encodeVarintPocValidationSnapshot(dAtA, i, uint64(m.ExchangeEndTimestamp))
		i--
		dAtA[i] = 0x30
	}
	if m.GenerationStartTimestamp != 0 {
		i = encodeVarintPocValidationSnapshot(dAtA, i, uint64(m.GenerationStartTimestamp))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ValidatorWeights) > 0 {
		for iNdEx := len(m.ValidatorWeights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorWeights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocValidationSnapshot(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AppHash) > 0 {
		i -= len(m.AppHash)
		copy(dAtA[i:], m.AppHash)
		i = encodeVarintPocValidationSnapshot(dAtA, i, uint64(len(m.AppHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SnapshotHeight != 0 {
		i = encodeVarintPocValidationSnapshot(dAtA, i, uint64(m.SnapshotHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.PocStageStartHeight != 0 {
		i = encodeVarintPocValidationSnapshot(dAtA, i, uint64(m.PocStageStartHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorWeight) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorWeight) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorWeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Weight != 0 {
		i = encodeVarintPocValidationSnapshot(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintPocValidationSnapshot(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPocValidationSnapshot(dAtA []byte, offset int, v uint64) int {
	offset -= sovPocValidationSnapshot(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoCValidationSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PocStageStartHeight != 0 {
		n += 1 + sovPocValidationSnapshot(uint64(m.PocStageStartHeight))
	}
	if m.SnapshotHeight != 0 {
		n += 1 + sovPocValidationSnapshot(uint64(m.SnapshotHeight))
	}
	l = len(m.AppHash)
	if l > 0 {
		n += 1 + l + sovPocValidationSnapshot(uint64(l))
	}
	if len(m.ValidatorWeights) > 0 {
		for _, e := range m.ValidatorWeights {
			l = e.Size()
			n += 1 + l + sovPocValidationSnapshot(uint64(l))
		}
	}
	if m.GenerationStartTimestamp != 0 {
		n += 1 + sovPocValidationSnapshot(uint64(m.GenerationStartTimestamp))
	}
	if m.ExchangeEndTimestamp != 0 {
		n += 1 + sovPocValidationSnapshot(uint64(m.ExchangeEndTimestamp))
	}
	return n
}

func (m *ValidatorWeight) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovPocValidationSnapshot(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovPocValidationSnapshot(uint64(m.Weight))
	}
	return n
}

func sovPocValidationSnapshot(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPocValidationSnapshot(x uint64) (n int) {
	return sovPocValidationSnapshot(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoCValidationSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocValidationSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCValidationSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCValidationSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartHeight", wireType)
			}
			m.PocStageStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotHeight", wireType)
			}
			m.SnapshotHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SnapshotHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocValidationSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocValidationSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorWeights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocValidationSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocValidationSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorWeights = append(m.ValidatorWeights, &ValidatorWeight{})
			if err := m.ValidatorWeights[len(m.ValidatorWeights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenerationStartTimestamp", wireType)
			}
			m.GenerationStartTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenerationStartTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangeEndTimestamp", wireType)
			}
			m.ExchangeEndTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExchangeEndTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocValidationSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocValidationSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorWeight) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocValidationSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorWeight: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorWeight: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocValidationSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocValidationSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocValidationSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocValidationSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPocValidationSnapshot(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPocValidationSnapshot
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocValidationSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPocValidationSnapshot
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPocValidationSnapshot
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPocValidationSnapshot
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPocValidationSnapshot        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPocValidationSnapshot          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPocValidationSnapshot = fmt.Errorf("proto: unexpected end of group")
)
